apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: tangming
  labels:
    app: es6
spec:
  replicas: 1   #指定Pod副本数
  selector:     #指定Pod的选择器
    matchLabels:
      app: es6
  template:
    metadata:
      labels:       #给Pod打label
        app: es6
    spec:
      containers:
      - name: es6
        image: nginx:1.14.2
        ports:
        - containerPort: 9200
        - containerPort: 9300
      env:
        - name: discovery.type
          value: single-node
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"    
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
        - name: localtime
          mountPath: /etc/localtime